remote_theme: fongandrew/hydeout

title: "Luke Sleeman"
description: "Principal Android Engineer & Team Leader"

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Navigation
sidebar_home_link: true

# Disable comments
disqus: false
